version: "3.8"
services:

  postgres:
    image: "postgres:12.4"
    container_name: "database"
    volumes:
      - pgdata:/var/lib/postgresql/data #persisting the database
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=database

  pyexec:
    build: "./pyexec"
    volumes:
      - ./ml_data:/data
    depends_on: 
        - postgres
        - pyml
        
  pyml:
    build: "./pyml"
    volumes:
      - ./ml_data:/data





volumes:
  pgdata:
  

